### ISSUE TITLE
Crash when playing with the recycler view and the animations

### ISSUE THREAD

**Issue by borombo-git** [PiotrPrus/MotionLayoutPlayground#2]
Hey, 

Here's the stack trace of the crash I get when playing around with the recyclerview and some animations : 

`2019-12-03 13:06:52.856 20493-20493/com.piotrprus.motionlayoutplayground E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.piotrprus.motionlayoutplayground, PID: 20493
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference
        at androidx.constraintlayout.motion.widget.MotionLayout$MyTracker.addMovement(MotionLayout.java:985)
        at androidx.constraintlayout.motion.widget.MotionScene.processTouchEvent(MotionScene.java:1043)
        at androidx.constraintlayout.motion.widget.MotionLayout.onTouchEvent(MotionLayout.java:2992)
        at android.view.View.dispatchTouchEvent(View.java:10023)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
        at android.view.View.dispatchPointerEvent(View.java:10243)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
2019-12-03 13:06:52.856 20493-20493/com.piotrprus.motionlayoutplayground E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

I got the same crash on my test app when I play too much with the recyclerView and the animations. I've also disabled touchEvent on the recyclerView when the animation starts and puts it back when the animation finishes ( but in a less clean way). So far, I guess the problem comes from the motionLayout view being null/deleted/not detected for some reason after an animation. 

PS : The crash mainly occurs when I try to scroll the list after I've executed an animation. 

I hope it helps!

**Comment by borombo-git** [comment]
A bit more information after playing with, the crash only occurs when you perform the animation and try to scroll the list, from outside the cell you played the animation from, but not every time. 
Example : 
Animation on Item2 + Scroll the list with a touch from the item 2 = OK
Animation on Item4 + Scroll the list with a touch from the item 6 = Crash

**Comment by PiotrPrus** [comment]
I found your question on stackOverflow: https://stackoverflow.com/questions/59104740/using-motionlayout-onswipe-on-item-of-a-recyclerview
The answer from Samuel Grogan works for me. Here is the kotlin version that make null checks for MotionTracker functions:
`package com.piotrprus.motionlayoutplayground.helper

import android.content.Context
import android.util.AttributeSet
import android.view.MotionEvent
import android.view.VelocityTracker
import androidx.constraintlayout.motion.widget.MotionLayout

class CustomMotionLayout : MotionLayout {
    constructor(context: Context?) : super(context)
    constructor(context: Context?, attrs: AttributeSet?) : super(
        context,
        attrs
    )

    constructor(
        context: Context?,
        attrs: AttributeSet?,
        defStyleAttr: Int
    ) : super(context, attrs, defStyleAttr)

    override fun obtainVelocityTracker(): MotionTracker {
        return MyTracker.obtain()
    }

    /**
     * The only functional changes to this class are added null-checks and recursion avoidance in
     *
     * @see MyTracker.getYVelocity
     */
    private class MyTracker private constructor() : MotionTracker {
        var tracker: VelocityTracker? = null
        override fun recycle() {
            tracker?.let {
                recycle()
                tracker = null
            }
        }

        override fun clear() {
            tracker?.clear()
        }

        override fun addMovement(event: MotionEvent) {
            tracker?.addMovement(event)
        }

        override fun computeCurrentVelocity(units: Int) {
            tracker?.computeCurrentVelocity(units)
        }

        override fun computeCurrentVelocity(
            units: Int,
            maxVelocity: Float
        ) {
            tracker?.computeCurrentVelocity(units, maxVelocity)
        }

        override fun getXVelocity(): Float {
            return tracker?.xVelocity ?: 0f
        }

        override fun getYVelocity(): Float {
            return tracker?.yVelocity ?: 0f
        }

        override fun getXVelocity(id: Int): Float {
            return tracker?.getXVelocity(id) ?: 0f
        }

        override fun getYVelocity(id: Int): Float {
            return tracker?.getYVelocity(id) ?: 0f
        }

        companion object {
            private val me =
                MyTracker()

            fun obtain(): MyTracker {
                me.tracker =
                    VelocityTracker.obtain()
                return me
            }
        }
    }
}`

**Comment by PiotrPrus** [comment]
@BBorombo Merged in PR number 4, currently on master. PLease test it out ;)
